kind: Service
apiVersion: v1
metadata:
  name: nodejs-app-service
  namespace: nodejs-app
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP